### ISSUE TITLE
💡[Feature]: Design a footer

### ISSUE THREAD

**Issue by komal-agarwal5** [chirantanbanik/Wellread#152] opened 2024-06-14 17:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a footer to the website

### Use Case

It would contain direct links to different sections as well as other details a footer contains

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment] 2024-06-15 06:22
@komal-agarwal5 This issue is the duplicate of the issue #37 and the work is assigned to two contributors. You can look upon other issues and work on them.

**Closed by chirantanbanik** 2024-06-15 06:22 UTC
Labels: duplicate
