### ISSUE TITLE
Implement 'Forgot Password' functionality

### ISSUE THREAD

**Issue by antriksh-9** [chirantanbanik/Wellread#34] opened 2024-05-15 08:18 UTC
**Is your feature request related to a problem? Please describe.**
For login page we must have a 'forgot password' option so that user can get access to their account if they didn't remember their password. Without a mechanism for password recovery, users may become frustrated or locked out of their accounts, resulting in a poor user experience.

**Describe the solution you'd like**

- When a user forgets their password, they would initiate the password reset process by clicking on a "Forgot Password".
- The user would be prompted to enter their email address associated with their account.
- The system would then send an email to the user's registered email address containing the password reset link.
- Then, the user can reset their password.

**Comment by antriksh-9** [comment] 2024-05-15 08:18
Hey @chirantanbanik, I want to work on this issue. 
Please assign me under GSSoC '24.

**Comment by antriksh-9** [comment] 2024-05-31 14:41
> Hey @chirantanbanik, I want to work on this issue. Please assign me under GSSoC '24.

@chirantanbanik

**Comment by chirantanbanik** [comment] 2024-06-10 04:36
Duplicate of the issue #84

**Closed by chirantanbanik** 2024-06-10 04:36 UTC
Labels: duplicate
